arb-dir: lib/core/localization/dictionaries
output-dir: lib/core/localization/gen
output-localization-file: app_localizations.g.dart
template-arb-file: app_ru.arb
synthetic-package: false
untranslated-messages-file: untranslated_messages_file.txt
