name: taro
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ^3.27.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Networking
  flutter_alice: ^2.0.1
  dio: ^5.9.0

  # UI
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  custom_refresh_indicator: ^4.0.1

  # Routing
  auto_route: ^10.0.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5

  # BLoC
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0

  # Storage
  shared_preferences: ^2.5.3

  # Other
  intl: ^0.19.0
  package_info_plus: ^8.3.0

  # Workspaces
  tarot_analytics:
    path: packages/tarot_analytics
  tarot_logger:
    path: packages/tarot_logger
  tarot_ui_kit:
    path: packages/tarot_ui_kit
  tarot_rest_client:
    path: packages/tarot_rest_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  mocktail: ^1.0.4
  alchemist: ^0.11.0
  flutter_launcher_icons: ^0.14.4

flutter_gen:
  output: lib/core/assets/gen/
  line_length: 120

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/

workspace:
  - packages/tarot_analytics
  - packages/tarot_logger
  - packages/tarot_ui_kit
  - packages/tarot_rest_client

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: assets/android_app_icon.png
  adaptive_icon_background: "#905CFB"
  adaptive_icon_foreground: assets/android_foreground.png
  ios: true
  image_path_ios: assets/ios_app_icon.png
  remove_alpha_ios: true
  min_sdk_android: 21
