name: taro
version: 0.1.0

environment:
  sdk: ^3.7.2
  flutter: ^3.29.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  flutter_svg: ^2.1.0

  # Other
  intl: ^0.19.0

  # Routing
  auto_route: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1

flutter_gen:
  output: lib/core/assets/gen/
  line_length: 120

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/TarotMeets.png

workspace:
  - packages/analytics
  - packages/logger
  - packages/ui_kit
  - packages/rest_client
