name: flutter_login
description: A login widget with login/signup functionalities to help speed up development
version: 5.1.0
repository: https://github.com/NearHuscarl/flutter_login
screenshots:
  - description: "This screenshot shows the default themed login screen.."
    path: demo/basic.png

environment:
  sdk: "^3.7.0"
  flutter: ">=3.16.0"

dependencies:
  another_flushbar: ^1.12.30
  another_transformer_page_view: ^2.0.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.0.0
  intl_phone_number_input: ^0.7.4
  phone_numbers_parser: ^9.0.0
  provider: ^6.0.1
  quiver: ^3.0.1
  sign_in_button: ^4.0.1
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ecorp.png

resolution: workspace
