name: tarot_logger
version: 1.0.0

environment:
  sdk: ^3.6.1
  flutter: ^3.27.3

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  firebase_crashlytics: ^4.3.5
  flutter_bloc: ^9.1.1
