name: tarot_ui_kit
version: 1.0.0

environment:
  sdk: ^3.6.1
  flutter: ^3.27.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  alchemist: ^0.11.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

resolution: workspace
