name: tarot_ui_kit
version: 1.0.0

environment:
  sdk: ^3.6.1
  flutter: ^3.27.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  alchemist: ^0.11.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.5.0+1

flutter:
  uses-material-design: true
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sf_pro_display/ultralight.otf
          weight: 100
        - asset: assets/fonts/sf_pro_display/thin.otf
          weight: 200
        - asset: assets/fonts/sf_pro_display/light.otf
          weight: 300
        - asset: assets/fonts/sf_pro_display/regular.otf
          weight: 400
        - asset: assets/fonts/sf_pro_display/medium.otf
          weight: 500
        - asset: assets/fonts/sf_pro_display/semibold.otf
          weight: 600
        - asset: assets/fonts/sf_pro_display/bold.otf
          weight: 700
        - asset: assets/fonts/sf_pro_display/heavy.otf
          weight: 800
        - asset: assets/fonts/sf_pro_display/black.otf
          weight: 900
flutter_gen:
  output: lib/assets/gen/
  line_length: 100
  assets:
    outputs:
      package_parameter_enabled: true

  integrations:
    flutter_svg: true

resolution: workspace
