name: tarot_analytics
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ^3.27.3

dependencies:
  firebase_analytics: ^11.4.5

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

resolution: workspace
